export const mockPosts = [
  {
    id: "1",
    title: "JavaScript has become much better to work with this year",
    author: "frontend_dev",
    score: 2450,
    comments: 184,
    permalink: "/r/javascript/",
  },
  {
    id: "2",
    title: "Why is debugging async JavaScript still so painful?",
    author: "codewizard",
    score: 1830,
    comments: 326,
    permalink: "/r/javascript/",
  },
  {
    id: "3",
    title: "I built my first full stack application today!",
    author: "newdeveloper",
    score: 3200,
    comments: 215,
    permalink: "/r/javascript/",
  },
  {
    id: "4",
    title: "What JavaScript framework are you using in 2026?",
    author: "webdev24",
    score: 986,
    comments: 403,
    permalink: "/r/javascript/",
  },
  {
    id: "5",
    title: "This new browser API is absolutely amazing",
    author: "jsfan",
    score: 4210,
    comments: 287,
    permalink: "/r/javascript/",
  },
  {
    id: "6",
    title: "Another dependency update broke our production build",
    author: "tiredengineer",
    score: 1510,
    comments: 198,
    permalink: "/r/javascript/",
  },
];